### ISSUE TITLE
workflow not working

### ISSUE THREAD

**Issue by sergiobayona** [actions/upload-pages-artifact#116]
I'm trying automate the documentation for a ruby gem at https://github.com/sergiobayona/VectorMCP with the following action:

```yaml
name: "Deploy YARD Docs"

on:
  push:
    branches:
      - main 
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: "Build YARD documentation"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.2 # use any version >= the gemspec requirement
          bundler-cache: true

      - name: Install dependencies (including YARD)
        run: |
          bundle install --jobs 4 --retry 3

      - name: Generate YARD documentation
        run: |
          bundle exec yard doc --quiet

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./doc

  deploy:
    name: "Deploy to GitHub Pages"
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
```

The action runs successfully and I expect the pages to appear at https://sergiobayona.github.io/VectorMCP/ but instead I get a 404 page. Any help appreciated.
