### ISSUE TITLE
action.yml still references actions/upload-artifact@main

### ISSUE THREAD

**Issue by SamStephens** [actions/upload-pages-artifact#23]
It should presumably reference actions/upload-pages-artifact.

```
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: github-pages
        path: ${{ runner.temp }}/artifact.tar
        retention-days: ${{ inputs.retention-days }}
```

https://github.com/actions/upload-pages-artifact/blob/fa880244ea08e3db8d86034fc4ecef66127fdf86/action.yml#62
