### ISSUE TITLE
Selecting specific files to archive requires additional steps

### ISSUE THREAD

**Issue by cyberf1y** [actions/upload-pages-artifact#28]
I want to archive a specific subset of the files in my repository.
Currenty, I must use the following steps, to achieve this:
```yaml
steps:
  - name: Create a site directory
    run: |
      shopt -s globstar &&
      tar -cvf site.tar **/*.html &&
      mkdir site &&
      tar -xf site.tar --directory site
      
  - name: Upload artifact
    uses: actions/upload-pages-artifact@v1
    with:
      path: 'site'
 ```
 This, apart from being error-prone, is not efficient, because of the unnecessary calls to `tar`.
 
 I think, that this could be achieved with the following:
 ```yaml
 steps:
   - name: Upload artifact
     uses: actions/upload-pages-artifact@v1
     with:
      path: '**/*.html'
 ```
 with very little change to [*action.yml*](https://github.com/actions/upload-pages-artifact/blob/fa880244ea08e3db8d86034fc4ecef66127fdf86/action.yml).
