### ISSUE TITLE
Customizable artifact name

### ISSUE THREAD

**Issue by jnonino** [actions/upload-pages-artifact#30]
Hi, it would be great if the artifact name can be customized. Right now it is hardcoded to the name `github-pages`.

```
- name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: github-pages
        path: ${{ runner.temp }}/artifact.tar
        retention-days: ${{ inputs.retention-days }}
```
