### ISSUE TITLE
set-output is deprecated

### ISSUE THREAD

**Issue by lukepighetti** [actions/upload-pages-artifact#31]
Getting this warning while using this action

```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

```yaml


on:
  push:
    branches: [lukepighetti/github-actions]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # ...

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
```
