### ISSUE TITLE
Support path exclusion

### ISSUE THREAD

**Issue by mara004** [actions/upload-pages-artifact#33]
When publishing Sphinx documentation, I noticed that the uploaded artifact is unnecessarily large because the `.doctrees` directory is included, so I tried to exclude it like this (as would be possible with `upload-artifact`):
```yaml
- name: Upload artifact
  uses: actions/upload-pages-artifact@v1
  with:
    path: |
      docs/build/html
      !docs/build/html/.doctrees
```
However, with `upload-pages-artifact`, this yield an error when calling `tar`:
```
tar: docs/build/html\n!docs/build/html/.doctrees\n: Cannot open: No such file or directory
```
