### ISSUE TITLE
Support for Windows-based workflows

### ISSUE THREAD

**Issue by microBob** [actions/upload-pages-artifact#4]
The "Upload Artifact" step is failing because `tar: Cannot connect to D: resolve failed`. I am trying to deploy a [Natural Docs](https://www.naturaldocs.org) documentation page which requires windows.

Steps to reproduce: 
1. Create a workflow that `runs-on: windows-latest`
2. `uses: action/configure-pages@v1` (no problems here)
3. Problem here 👇
```yaml
uses: actions/upload-pages-artifact@v1
with:
        path: '.\docs'
```
