### ISSUE TITLE
`path` parameter is not sensitive to job's `default.run.working-directory` parameter

### ISSUE THREAD

**Issue by menzenski** [actions/upload-pages-artifact#52]
I am using this action in a workflow that generates dbt project documentation and then deploys that documentation to GitHub pages. Following the readme file in [actions/deploy-pages](https://github.com/actions/deploy-pages#usage) I have two jobs in my workflow, a `build_docs` job that generates the documentation and uses this `actions/uploads-pages-artifact` to upload it, and then a `publish_docs` job which needs the `build_docs` job and which uses `actions/deploy-pages` to deploy to GitHub pages.

The issue I have run into is that I am setting a `defaults.run.working-directory` parameter, and that is not respected by the `path` parameter of the `upload-pages-artifact` action. If I set a working-directory, my expectation is that any path I specify in the action will be interpreted relative to that working directory, but this is not the case here. 

I did get this working but it requires setting the `path` relative to the repository's root directory, not the configured working directory for the job. 

```yaml
# name etc truncated

jobs:

  build_docs:
    name: Build and upload docs artifact
    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: src

    environment:
      name: dev

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      # generating the docs happens here

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: dbt_docs
          path: src/.meltano/transformers/dbt/target

  publish_docs:
    name: Publish dbt docs to GitHub Pages
    runs-on: ubuntu-20.04

    needs:
      - build_docs

    permissions:
      contents: read
      pages: write
      id-token: write

    concurrency:
      group: pages
      cancel-in-progress: true

    environment:
      name: dev

    steps:

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          artifact_name: dbt_docs
```
