### ISSUE TITLE
Support setting $GITHUB_OUTPUT with a one-liner

### ISSUE THREAD

**Issue by dlmiles** [actions/upload-pages-artifact#60]
This is to allow another workflow to know this action has been performed during this run.

outputs.key would be a fixed string
outputs.value can be a fixed string, or anything allowed as an expression

```
- name: Upload github-pages
  uses: actions/upload-pages-artifact@main
  with:
    name: github-pages
    path: dist/gh-pages
    retention-days: 90
  outputs:
  - key: fixed-string
    another: can ${{ maybe }} use expression ${{ env.foo }} as well in value but key is fixed string
    deploy: true
```

The oneliner version might look like:

```
- id: thisid
  uses: actions/upload-pages-artifact@main
  outputs: true
```

In this form the OUTPUTS might have been set as "thisid=true" or "output=true".

Just the same as reported here:  https://github.com/actions/upload-artifact/issues/220#issuecomment-1543498219
