### ISSUE TITLE
Accept a `run` parameter to build the artifact before publishing it

### ISSUE THREAD

**Issue by NatoBoram** [actions/upload-pages-artifact#9]
Some frameworks would benefit form knowing if the build they are doing is going to be published on GitHub Pages. For example, [SvelteKit](https://github.com/sveltejs/kit) supports building for Vercel, Cloudflare Pages and Netlify by checking for the environment variables `VERCEL`, `CF_PAGES` and `NETLIFY`.

Currently, there aren't any way for a framework to check if the environment it's building for is GitHub Pages. One could check for `GITHUB_ACTIONS`, but that's [a little too broad](https://github.com/sveltejs/kit/pull/5845#discussion_r939639888) for this purpose.

A solution to this problem would be to allow this action to receive and execute an arbitrary command to make the build it's going to publish.

#### Before

```yaml
      - name: Build
        run: pnpm run build
      - uses: actions/upload-pages-artifact@v1.0.1
        with:
          path: build
      - uses: actions/deploy-pages@v1.0.7
```

#### After

```yaml
      - uses: actions/upload-pages-artifact@v1.0.1
        with:
          run: |
            pnpm run build
          path: build
      - uses: actions/deploy-pages@v1.0.7
```

This way, a framework which wants to auto-detect if it's building for GitHub Pages would be able to use `GITHUB_ACTION_REPOSITORY == "actions/upload-pages-artifact"`.

**Comment by AndrewLester** [comment]
Could [actions/configure-pages](https://github.com/actions/configure-pages) set a new environment variable for the rest of the workflow (e.x. `GITHUB_PAGES`)? Not sure if this is technically possible, and it may be more error-prone than this solution.

**Comment by NatoBoram** [comment]
If it can do it, I think it would be great. It would offer an easy and official way to separate pipelines that are used for deployment from those used for testing and frameworks would be able to rely on it.

**Comment by AndrewLester** [comment]
First of all, thanks so much for working on these new GitHub pages features.

> For a bunch of Node-based static site generators unfortunately their configuration is pure JavaScript and very painful to inject. So we do it by [parsing the abstract syntax tree](https://github.com/actions/configure-pages/blob/404d23c4a6f35881831e332b4d8c5a3f7ef487f5/src/config-parser.js) of an expected configuration file...

Since it seems like GitHub pages is taking the route of automatically configuring some static site generators, as opposed to setting a bunch of environment variables and letting the generators themselves do the work (some can't, so this solution does help), is there an opportunity for the community to contribute code for other static site generators in `actions/configure-pages` and `actions/starter-workflows`? From what I could tell, `actions/starter-workflows` is currently not accepting community submissions, but this may not reflect the newer static site generation workflows.

> Telling a static site generator it is building for GitHub Pages is not sufficient. It would rather know what's the URL, the path prefix (if different than /), etc.

While this is true, if the static site generator is automatically configured (with `actions/configure-pages`), then it will already know these things. In some cases SSG cases, ([SvelteKit](https://kit.svelte.dev/), for example), certain configuration file _imports_ need to be changed to adapt the site to its static form, _unless_ SvelteKit can know that the site should be statically adapted _by itself_, which in SvelteKit's case is done by checking [environment variables](https://github.com/sveltejs/kit/tree/master/packages/adapter-auto). It just checks for certain system environment variables and adapts the site accordingly.

For example, if SvelteKit detected that `GITHUB_PAGES` was set, it would use its static adapter (without requiring the user to change configuration file imports).

To be clear, our reasoning for setting a `GITHUB_PAGES` environment variable in `actions/configure-pages` is centered around SvelteKit, a full stack JS framework that doesn't even have a starter workflow yet. That said, I think adding this variable could be suitable for many other full stack JS frameworks that use an "adapter" system, such as [Remix](https://remix.run/docs/en/v1/other-api/adapter), and therefore make using GitHub Pages with these projects more seamless.

**Comment by NatoBoram** [comment]
Right now, if I understand it correctly, one would have to capture the outputs and manually register them to add them to the environment variables.

```yaml
      - uses: actions/configure-pages
        id: configure-pages
      - name: Build
        env:
          GITHUB_PAGES: true
          BASE_PATH: ${{ steps.configure-pages.outputs.base_path }}
        run: pnpm run build
      - uses: actions/upload-pages-artifact@v1.0.1
        with:
          path: build
      - uses: actions/deploy-pages@v1.0.7
```

This is fine for individual project and repos, but ideally we would want GitHub Pages to be officially supported, with zero config, from the framework itself, without having to modify the workflow file and without parsing the configuration file. Something like [this](https://github.com/actions/upload-pages-artifact/issues/9#issuecomment-1207603533).

To achieve that, `actions/configure-pages` could be modified at `src/output-pages-base-url.js` for this:

```javascript
const core = require("@actions/core")

function outputPagesBaseUrl(siteUrl) {
  core.setOutput("base_url", siteUrl.href)
  core.setOutput("origin", siteUrl.origin)
  core.setOutput("host", siteUrl.host)
  core.setOutput("base_path", siteUrl.pathname)

  core.exportVariable("GITHUB_PAGES", true)
  core.exportVariable("BASE_URL", siteUrl.href)
  core.exportVariable("ORIGIN", siteUrl.origin)
  core.exportVariable("HOST", siteUrl.host)
  core.exportVariable("BASE_PATH", siteUrl.pathname)
}

module.exports = outputPagesBaseUrl
```

This way, static sites generators would be able to look for `$GITHUB_PAGES` and automatically configure themselves without needing their configuration file parsed or some other wizardry.
